[colors.bright]
black = "#686868"
blue = "#59C2FF"
cyan = "#95E6CB"
green = "#C2D94C"
magenta = "#FFEE99"
red = "#F07178"
white = "#FFFFFF"
yellow = "#FFB454"

[colors.normal]
black = "#01060E"
blue = "#53BDFA"
cyan = "#90E1C6"
green = "#91B362"
magenta = "#FAE994"
red = "#EA6C73"
white = "#C7C7C7"
yellow = "#F9AF4F"

[colors.primary]
background = "#181818"
foreground = "#B3B1AD"

[cursor]
style = "Beam"

[font]
size = 13

[font.normal]
family = "JetbrainsMono Nerd Font"

[scrolling]
history = 5000

[window]
dynamic_padding = true
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 100
lines = 27

[window.padding]
x = 6
y = 0

[shell]
program = "C:/Program Files/PowerShell/7/pwsh.exe"
args = [ "-WorkingDirectory C:/Users/Rumman" ]

